#!/usr/bin/env bash

set -eu

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

#while true; do echo -e "HTTP/1.1 200 OK\n\n $(date)" | nc -l 0.0.0.0 5000; done

pip install -r "$DIR"/lib/fprime/requirements.txt

cd "$DIR"/DtnRef
rm -rf build-fprime-*
fprime-util generate aarch64-linux
fprime-util build aarch64-linux
fprime-gds --gui-addr 0.0.0.0
