#!/usr/bin/env bash

set -eu

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
readonly CONTAINER='fprime'

docker rm -f "$CONTAINER" 2>/dev/null || true
docker build -t "$CONTAINER" -f "$DIR"/fprime.dockerfile "$DIR"

docker run \
    -v "$DIR"/DtnRef:/home/ptl/DtnRef \
    -v "$DIR"/lib:/home/ptl/lib \
    -v "$DIR"/entrypoint:/home/ptl/entrypoint \
    -it \
    -p 5555:5000 \
    --name "$CONTAINER" \
    --entrypoint bash \
    "$CONTAINER" \
    -c './entrypoint; bash'
