#!/usr/bin/env bash

set -eu

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
readonly NETWORK='dtn-network'
readonly FSW_CONTAINER='fprime-dtn'
readonly GDS_CONTAINER='fprime-gds'

if [[ $# -gt 0 ]]; then
    readonly DOCKER_MODE_ARG="$1"
else
    readonly DOCKER_MODE_ARG='-it'
fi

build()
{
    local CONTAINER="$1"
    docker rm -f "$CONTAINER" 2>/dev/null || true
    docker build -t "$CONTAINER" -f "$DIR"/fprime.dockerfile "$DIR"
}

run()
{
    local CONTAINER="$1"; shift
    local ENTRYPOINT="$1"; shift
    local IP="$1"; shift
    local MODE_ARG="$1"; shift
    local PUBLISH_ARG="$@"

    # `/dev/shm` is sized to support ION shared memory needs
    docker run \
        --shm-size=1gb \
        -v "$DIR"/Dtn:/home/ptl/Dtn \
        -v "$DIR"/Ref:/home/ptl/Ref \
        -v "$DIR"/lib/fprime-gds-dtn:/home/ptl/lib/fprime-gds-dtn \
        -v "$DIR"/entrypoint:/home/ptl/entrypoint \
        $MODE_ARG \
        --network "$NETWORK" \
        --ip "$IP" \
        $PUBLISH_ARG \
        --name "$CONTAINER" \
        --entrypoint bash \
        "$CONTAINER" \
        -c "$ENTRYPOINT"
}

build "$FSW_CONTAINER"
build "$GDS_CONTAINER"

docker network rm "$NETWORK" 2>/dev/null || true
docker network create "$NETWORK" --subnet 10.0.0.0/8

# To attach to GDS: `docker attach fprime-gds`
# Using 127.0.0.1 to only publish port mapping for local interface
run "$GDS_CONTAINER" \
    'entrypoint/gds-entrypoint 10.0.0.3 10.0.0.2 ; bash' \
    '10.0.0.3' \
    -dit \
    --publish 127.0.0.1:5555:5000

run "$FSW_CONTAINER" \
    'entrypoint/deployment-entrypoint 10.0.0.2 10.0.0.3 ; bash' \
    '10.0.0.2' \
    $DOCKER_MODE_ARG
