#!/usr/bin/env python3
import pyion

    
EID_NAME = 'ipn:3.1'


if __name__ == '__main__':
    # Create a proxy to node 1 and attach to it
    proxy = pyion.get_bp_proxy(1)

    # Listen to 'ipn:3.1' for incoming data
    with proxy.bp_open(EID_NAME) as eid:
        print(f'[bp-print] Running on {EID_NAME}')
        while eid.is_open:
            try:
                # This is a blocking call
                print('Bundle:\n', eid.bp_receive())
                print()
            except InterruptedError:
                # User has triggered interruption with Ctrl+C
                break
