#!/usr/bin/env bash

set -eu

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
readonly OWN_ADDR="$1"
readonly DEST_ADDR="$2"

#while true; do echo -e "HTTP/1.1 200 OK\n\n $(date)" | nc -l 0.0.0.0 5000; done

# ION

cd /home/ptl/lib/ion-core
scripts/extract.sh ../ion-open*

make linux
make install
scripts/host.sh "$OWN_ADDR" "$DEST_ADDR"
scripts/ionstart -I host*.rc
