#!/usr/bin/env bash

set -eu

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

# ION

cd /home/ptl/lib/ion-core
ionstart -I host2.rc
cd -

cd /home/ptl/lib/ion
mkdir -p /home/ptl/Dtn/Dtn/lib/ion
cp .libs/lib{bp,ici,ltp}.a /home/ptl/Dtn/Dtn/lib/ion

mkdir -p /home/ptl/Dtn/Dtn/include/ion
cp /home/ptl/lib/ion-core/inc/* /home/ptl/Dtn/Dtn/include/ion

# F PRIME

cd /home/ptl/Ref
rm -rf build-fprime-*

run-release()
{
    fprime-util generate #aarch64-linux
    fprime-util build -j4 #aarch64-linux

    build-artifacts/Linux/Ref/bin/Ref \
        -a 10.0.0.3 \
        -p 50000
    #. /home/ptl/fprime-venv/bin/activate
    #fprime-gds --gui-addr 0.0.0.0 # Run on any subnet
}

run-debug()
{
    fprime-util generate --ut #aarch64-linux
    cd build-*-ut
    make Ref

    # Ignore SIG32 to avoid breaking on nominal pthread cancellation signal.
    # Add `-ex=r` to run immediately
    gdb -ex 'handle SIG32 nostop' \
        -ex 'r' \
        --args bin/Linux/Ref \
        -a 10.0.0.3 \
        -p 50000
}

#run-debug
run-release
