#!/usr/bin/env bash

set -eu

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

"$DIR"/common-entrypoint "$@"

set -x

#"$DIR"/../ltp-test/run
#"$DIR"/bp-transmit
#while true; do echo -e "HTTP/1.1 200 OK\n\n $(date)" | nc -l -q 0 0.0.0.0 5000; done

# Using 0.0.0.0 to run on any subnet
fprime-gds -n \
    --dictionary /home/ptl/RefTopologyAppDictionary.xml \
    --gui-addr 0.0.0.0
# TODO have GDS container take built XML dict in a less hardcoded manner
