#!/usr/bin/env bash

set -eu

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

"$DIR"/common-entrypoint -u "$@"

set -x

/home/ptl/entrypoint/bp-print
#/home/ptl/entrypoint/bp-transmit
